### ISSUE TITLE
Acurafixril isn't needed anymore

### ISSUE THREAD

**Issue by danielstuart14** [dorimanx/DORIMANX_LG_STOCK_LP_KERNEL#12]
Since now you created a d805 kernel build with cloudy ril fix, we don't need the old "acurafixril" anymore.
 (It'll break cloudy fix, and it isn't working as it should.)

So, just revert https://github.com/dorimanx/DORIMANX_LG_STOCK_LP_KERNEL/commit/930ddcc648fe71f90da944c87c3d367001a66b7c

It would be awesome if you add d805 builds in your site, too. :cow2::dash: :dancers:

**Comment by dorimanx** [comment]
Already removed the accura ril fix run, files remain for tests... they not executed on boot, with any model. When i will have working solution for d805 i will add it to site and xda. I dont have it yet.
