### ISSUE TITLE
d805 variant = not needed anymore

### ISSUE THREAD

**Issue by danielstuart14** [dorimanx/DORIMANX_LG_STOCK_LP_KERNEL#13]
As d805 get today oficial lollipop (with the latest modem), we don't need anymore to compile a standalone version for this device. D802 kernel version will work without the gsm problems we were facing.

**Comment by danielstuart14** [comment]
http://csmgdl.lgmobile.com/dn/downloader.dev?fileKey=FW79X6M232BRAPY46EA8ZS1/D80530A_00.kdz

**Comment by dorimanx** [comment]
thanks. removed already.
