### ISSUE TITLE
lm3630 backlight driver update(s)

### ISSUE THREAD

**Issue by danielstuart14** [dorimanx/DORIMANX_LG_STOCK_LP_KERNEL#4]
It's not a issue, but here is a list with a lot of fixes/updates for backlight driver:
https://github.com/franciscofranco/hammerhead/commits/lollipop-mr1/drivers/video/backlight/lm3630_bl.c

(lm3630_bl.c >>> lm3630.c)

**Comment by dorimanx** [comment]
https://github.com/dorimanx/DORIMANX_LG_STOCK_LP_KERNEL/commit/050e972ce2a2dd5b89c1b27ee9f98bbcaf198b9d
