### ISSUE TITLE
ISSUE: Min Backlight Override Switch (bellow 24% of brightness)

### ISSUE THREAD

**Issue by danielstuart14** [dorimanx/DORIMANX_LG_STOCK_LP_KERNEL#5]
I noticed that when I set "Min Backlight Override Switch" ON, and try to use manual brightness slide bar, anything bellow 24% doesn't seems to make difference on lux.

**Comment by dorimanx** [comment]
min backlight brightness is 3% = level 50.
it's now can be used, or set higher if too dark
https://github.com/dorimanx/DORIMANX_LG_STOCK_LP_KERNEL/commit/050e972ce2a2dd5b89c1b27ee9f98bbcaf198b9d
